# Generated by Django 3.1.5 on 2021-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(default=1, max_length=16, verbose_name='Тэг вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата вопроса'),
        ),
    ]
