# Generated by Django 3.1.3 on 2020-11-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
