# Generated by Django 3.1.5 on 2021-01-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210117_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
