# Generated by Django 3.1.5 on 2021-01-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='200.jpg', upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
