# Generated by Django 3.1.3 on 2020-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
