# Generated by Django 3.1.5 on 2021-01-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210117_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='uploads/200.jpg', upload_to='avatar/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
