# Generated by Django 3.1.3 on 2020-12-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='a',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
