# Generated by Django 3.1.3 on 2020-12-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a',
        ),
    ]
