# Generated by Django 3.1.5 on 2021-01-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210117_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Rate'),
        ),
        migrations.CreateModel(
            name='RatingUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to='app.profile', verbose_name='Rated user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='app.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': "Users' rating",
                'verbose_name_plural': "Users' ratings",
            },
        ),
        migrations.CreateModel(
            name='RatingQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Users')),
            ],
            options={
                'verbose_name': "Questions' rating",
                'verbose_name_plural': "Questions' ratings",
            },
        ),
        migrations.CreateModel(
            name='RatingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer', verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='User')),
            ],
            options={
                'verbose_name': "Answers' rating",
                'verbose_name_plural': "Answers' ratings",
            },
        ),
    ]
