# Generated by Django 3.1.3 on 2020-12-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_question_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count_answers',
            field=models.IntegerField(default=0, verbose_name='Кол-во ответов'),
            preserve_default=False,
        ),
    ]
