# Generated by Django 3.1.3 on 2020-12-01 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_question_count_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата вопроса'),
            preserve_default=False,
        ),
    ]
