# Generated by Django 3.1.5 on 2021-01-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
