# Generated by Django 3.1.5 on 2021-01-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210113_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=1, verbose_name='Дата вопроса'),
        ),
    ]
