# Generated by Django 3.1.5 on 2021-01-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210113_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата вопроса'),
        ),
    ]
