# Generated by Django 3.1.5 on 2021-01-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
    ]
